modLoader="javafml" #mandatory
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
	modId="femalevillagers"
	version="1.4"
	displayName="Female Villagers"
	authors="Daripher"
	description='''Adds female villagers'''

[[dependencies.femalevillagers]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.femalevillagers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
